modLoader="javafml"
loaderVersion="[34,)"
license="MIT License"

[[mods]]
modId="mineria"
version="1.2.0"
displayName="Mineria"
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://mineria-update.fr/" #optional
logoFile="logo.png" #optional
credits="Coded by LGatodu47" #optional
authors="Mathys_craft, Mr-lulu-51, LGatodu47"
description='''
The main mod of Mineria, a Modded PVP-Faction server."
'''

[[dependencies.mineria]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.mineria]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3,1.17)"
    ordering="NONE"
    side="BOTH"